### ISSUE TITLE
high circlesize bonus should cap at 5

### ISSUE THREAD

**Issue by Francesco149** [oamaok/ezpp#10]
this is my fault, I forgot to cap the cs bonus (which is probably how it worked prior to the high cs nerf after WWW's 600pp score)

see this commit https://github.com/Francesco149/oppai/commit/0b028e6a00a1a715f8a375bf3fa3ec7cc7f3939f

it fixes extreme overrating of maps like https://osu.ppy.sh/s/347136

**Comment by oamaok** [comment]
Fixed [here](https://github.com/oamaok/ezpp/commit/b58c7d51c9cc4ecc1c503d952ed5a2a43ebdfdb4) and [here](https://github.com/oamaok/osu-pp-calculator/commit/a5074e7b7b449a37745a66ae49c61a1bc4a678ac).

**Comment by oamaok** [comment]
For some reason the patch only caused minor pp reduction, will investigate further.

**Comment by oamaok** [comment]
Resolved by using ojsama
