### ISSUE TITLE
Maybe create a new repo for calculating?

### ISSUE THREAD

**Issue by acrylic-style** [oamaok/ezpp#100]
Currently, the taiko calculation codes are in ezpp repository, instead of its dedicated repo/package.
I think we can create another repo for these calculation codes.
If we *don't* publish the package to npm, then we can do `yarn add oamaok/new-repo` to add a package that is from a github repo.

**Comment by oamaok** [comment]
Creating an npm package for this would be great, since ojsama only has support for standard. If we publish a full-fledged package with the ability to calculate all the gamemodes, we will create much value for other people as well.

**Comment by oamaok** [comment]
Alternatively, we could take a monorepo approach. This repo would contain both the extension and the calculators as separate projects in separate yarn workspaces. We could then publish an npm package called `ezpp`, more people would find it if we just reuse the name for the npm package as well.

**Comment by oamaok** [comment]
Created a new repo, will set it up later today: https://github.com/oamaok/libezpp
