### ISSUE TITLE
[meta] enable discussion feature?

### ISSUE THREAD

**Issue by acrylic-style** [oamaok/ezpp#102]
I think the it would make people easier to discuss with someone, like quick questions that doesn't worth opening an issue, or just talking about something related to ezpp!.
Also, I am not too familiar with this feature since it's pretty new feature, but it may be easier than a Discord server, because we can search/track the discussion.

**Comment by oamaok** [comment]
![image](https://user-images.githubusercontent.com/3877125/112596172-1e133f00-8e14-11eb-8387-e84eae9f6aef.png)
