### ISSUE TITLE
Add taiko support

### ISSUE THREAD

**Issue by oamaok** [oamaok/ezpp#12]
Somewhat accurate calculator can be found here: http://pp.mon.im/

**Comment by christopher-dG** [comment]
https://github.com/Francesco149/oppai-ng supports taiko now :smile:

**Comment by oamaok** [comment]
woop, gonna port the new version when i have the stamina.

**Comment by christopher-dG** [comment]
Make sure to not compile it yourself and use the binary that's on the releases page: https://github.com/Francesco149/oppai-ng/issues/12

**Comment by oamaok** [comment]
i don't use the binary or oppai at all, i ported the last version to typescript and used it.

**Comment by christopher-dG** [comment]
Ah cool :+1:

**Comment by oamaok** [comment]
Initial taiko support added: https://github.com/oamaok/ezpp/pull/70
