### ISSUE TITLE
No longer supports legacy website

### ISSUE THREAD

**Issue by litgib** [oamaok/ezpp#18]
"An error prevented the extension from working properly: html.match(...) is null"

**Comment by oamaok** [comment]
Identified the error, but I'm unable to resolve it cleanly at this time. I'm also not able to reproduce it consistently. I'll leave the issue open for now.

**Comment by litgib** [comment]
Sorry should have mentioned my browser I guess, consistently happens for me on firefox - just tried on chrome and I can't seem to reproduce.

**Comment by oamaok** [comment]
Can you confirm whether the issue is still relevant or not? After the last few updates the extension seems to work well on both sites, both Chrome and Firefox.

**Comment by litgib** [comment]
It's worked fine for me on firefox since you updated it.
