### ISSUE TITLE
Feature Request: Translations

### ISSUE THREAD

**Issue by DJNeonNight** [oamaok/ezpp#20]
I know the extension may not have too many strings to translate, but it would be nice to have the option for people that don't know much of English. Anyways, I'm available for Spanish translations if needed.

**Comment by oamaok** [comment]
Added support for translations, you can find the base English translation here: https://github.com/oamaok/ezpp/tree/master/src/translations
If you want to add a translation also fill the relevant info here to enable it: https://github.com/oamaok/ezpp/blob/master/src/js/translations.js#L1-L14
