### ISSUE TITLE
Display pp for loved and qualified maps

### ISSUE THREAD

**Issue by Poyo-SSB** [oamaok/ezpp#37]
Displaying a calculated value instead of the 0 that's given by the website would nice. Perhaps it would be colored yellow or in parentheses or something like that to indicate that it's not an official, effective value.

**Comment by oamaok** [comment]
Sorry for the late response!

I'm planning on having this extension to be popup-only. This keeps the maintenance of the extension easily manageable for me, as having the extension affect the site itself would require constant keep up with the changes on the site structure. Additionally I don't want to introduce what-some-may-call distruptive changes when the extension has been self-contained so long.

There are other extensions/userscripts such as osuplus which do affect the site, so I guess you could ask for them to add this feature.

Sorry to disappoint and thank you for understanding.
