### ISSUE TITLE
HT AR is not accurate

### ISSUE THREAD

**Issue by Purplegaze** [oamaok/ezpp#74]
Base AR is 7.5 here and it shows 14.1 with HT

![](https://cdn.discordapp.com/attachments/247078580381679627/823580769980776488/unknown.png)

**Comment by oamaok** [comment]
Thanks for reporting!

**Comment by acrylic-style** [comment]
![image](https://user-images.githubusercontent.com/19150229/112022976-24848b00-8b76-11eb-8c70-57dad1922718.png)
AR with HT seems completely wrong, I'll look into it.
