### ISSUE TITLE
Incorrect AR displayed with DTHR and no AR changing mods

### ISSUE THREAD

**Issue by Flamiii** [oamaok/ezpp#81]
Noticed ezpp got an update with an additional number next to the BPM, which I'm assuming signifies AR.

Either way, this number seems to be accurate with AR changing mods like EZ, HR, DT, and HT, but without them, it always says the AR is 11. I tried this on multiple maps, but it always seemed to have this issue. Hopefully it will get resolved soon.

**Comment by Flamiii** [comment]
Also just figured out that DTHR tends to have the wrong AR. On most maps, it should be AR 11, but DTHR just ends up making the AR equivalent to the map's AR by default. For example, https://osu.ppy.sh/beatmapsets/1228487#osu/2822288 +DTHR on this map causes ezpp to display the map's AR as 9.4 with DTHR, when it should be AR 11. 

![2021-03-22_21-08-37](https://user-images.githubusercontent.com/74088315/112082227-f9d50b00-8b52-11eb-8353-b48276249afc.png)

**Comment by acrylic-style** [comment]
Already fixed in the latest commit, so you just need to wait until the v1.10.1 release.

**Comment by Flamiii** [comment]
Alright, sounds good.
