### ISSUE TITLE
AR is displayed incorrectly

### ISSUE THREAD

**Issue by yashbxyz** [oamaok/ezpp#84]
Not sure exactly what's wrong, AR is displayed as 11 without any mods and then displayed correctly with 1 mod, but not correct with multiple mods

**Comment by yashbxyz** [comment]
Example: https://osu.ppy.sh/beatmapsets/1084605#osu/2268176

**Comment by yashbxyz** [comment]
Example map: https://osu.ppy.sh/beatmapsets/1084605#osu/2268176

Approach rate of map is 9.7, displayed as 11 on the extension
![image](https://user-images.githubusercontent.com/24298792/112154158-00728980-8c0a-11eb-88cb-8f4a36cffdb3.png)

**Comment by acrylic-style** [comment]
- duplicate of #74, #81
- this bug is already fixed (#76) but waiting for the v1.10.1 release

**Comment by oamaok** [comment]
let's leave this one open until we get the next release out, so people find it easier.

**Comment by yashbxyz** [comment]
Sorry for not checking closed issues! Thanks!

**Comment by oamaok** [comment]
Update queued on both Google Web Store and Mozilla Add-Ons.
