### ISSUE TITLE
For the ezpp window to not close when tabbing out

### ISSUE THREAD

**Issue by goorilla** [oamaok/ezpp#90]
**Is your feature request related to a problem? Please describe.**
When you tab out and you have a ezpp window open, it closes out.

**Describe the solution you'd like**
A setting to disable it closing out when you tab out of the chrome window, and adds a button to close it out when you have that setting on.

**Describe alternatives you've considered**
Maybe just make it so it wont close out and there is a button to close it instead of a setting

**Comment by oamaok** [comment]
Thanks for posting! Unfortunately this is an UI decision by browser developers, and we cannot alter that behavior. The opening and closing of the extension window is out of our control.
